### ISSUE TITLE
Loading module and namespaced classes from directory structure

### ISSUE THREAD

**Issue by milgner** [fxn/zeitwerk#113]
As someone with a Rails background, I am accustomed for this to work:

```
# app/mymodule.rb
module Mymodule
end
```

```
# app/mymodule/myclass.rb
module Mymodule
  class Myclass
  end
end
```

Now that Rails 6 uses Zeitwerk, when trying to autoload `Mymodule::Myclass`, it stops looking after finding `app/mymodule.rb`, raises a `NameError` and does not descend into the subfolder anymore.

It works after deleting the empty module file, but that's only possible as long as it remains empty: usually this file is used to override defaults like table name prefixes for classes of the module.

Is it a user error, bug or maybe just a problem of the integration of Zeitwerk into Rails?

**Comment by fxn** [comment]
For that to work, you need to have `app` in the autoload paths. Doing so is a bad practice because the mapping file name <-> constant is ambiguous. That is, you no longer know if `app/models/user.rb` should define `User` or `Models::User`.

Zeitwerk makes this deterministic on purpose by making [nested root directories](https://github.com/fxn/zeitwerk#nested-root-directories) have higher priority.

Please do not put `app` in the autoload paths.

**Comment by milgner** [comment]
I don't think I follow your reasoning. The auto loading of `Mymodule::Myclass` from `app/mymodule/myclass.rb` works just fine if there's no `app/mymodule.rb`. Just the same for just loading the `Mymodule` constant from `app/mymodule.rb`. This is a standard Rails 6 setup, so if `app` is the autoload paths - which I can't verify right this moment unfortunately - it wasn't explicitly put there.

What approach do you suggest for situations where you want to define or execute module-level methods and classes without putting them into one file?

**Comment by fxn** [comment]
Could you double check please?

In a Rails application, `app/mymodule/foo.rb` defines `Foo`, not `Mymodule::Foo`, because Rails configures `app/mymodule` to be an autoload path just like `app/models` is. That is, unless you're in classic mode and `app` is added manually to the autoload paths.

Zeitwerk supports namespaces as usual. For a directory to be a namespace, it has to be a descendant of the root directories, which represent `Object`. So, `app/models/admin/user.rb` may define `Admin::User`, and you can have `app/models/admin.rb` if you like. `app/admin/user.rb` cannot define `Admin::User`.

**Comment by milgner** [comment]
Shame on me: the files are not directly in `app/` but in `app/models` - just goes to show that working late can kill ones concentration and lead to silly errors.

Unfortunately the rest of the problem applies: with Zeitwerk active, autoloading stops after finding the file that contains the module without trying to descend into the corresponding module folder. Deleting the module file makes things work again.

**Comment by fxn** [comment]
That can't be, something weird must be going on.

Could you please throw

```ruby
Rails.autoloaders.log!
```

in `config/application.rb`, trigger the error, and share the output?

**Comment by milgner** [comment]
Will do once I'm back at work tomorrow! :+1: Actually we narrowed down the problem by using `Rails.autoloaders.log!` and seeing that it raised `NameError` after loading the `mymodule.rb`. 
Thank you so much for your timely support!

**Comment by fxn** [comment]
This happens in the context of a Rails application, so I have moved the issue to https://github.com/rails/rails/issues/38726.

**Comment by FelipeRiveraC** [comment]
Hello, have you found any workaround for this issue?

I am having this exact same problem. A solution would be having a namespace unique by name and defining the table names in each record.

This breaks a little the point of namespaces.

Do you have any other solutions?

**Comment by fxn** [comment]
For the archives, conversation has followed in the Rails issue linked above.
