### ISSUE TITLE
Reloading code on changes not working

### ISSUE THREAD

**Issue by Kroid** [fxn/zeitwerk#121]
Same issue as in https://github.com/fxn/zeitwerk/issues/50, but listener gem don't help.

```
macOS
ruby 2.7.0
zeitwerk (2.3.0)
```

app/environment.rb
```ruby
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __dir__)
require 'bundler/setup'

ENV['RACK_ENV'] ||= 'development'
Bundler.require(*[:default, ENV['RACK_ENV']])
```

app/boot.rb
```ruby
require_relative 'environment'

loader = Zeitwerk::Loader.new
loader.push_dir('app')

unless ENV['RACK_ENV'] == 'production'
  loader.enable_reloading
  loader.log!
  Listen.to('app') { loader.reload }.start
end

loader.setup
```

app/application.rb
```ruby
require_relative 'boot'
```

config.ru
```ruby
require_relative 'app/application'
run Router.new
```

app/router.rb
```ruby
class Router
  def call(env)
    [200, {'Content-Type' => 'text/html'}, ["Hello World"]]
  end
end
```

I started web server with `bundle exec rackup`. Changes in Router class have no effect. But in stdout we see the code reloaling:
```
Zeitwerk@9ed483: autoload for Router removed
Zeitwerk@9ed483: autoload set for Router, to be loaded from /.../app/router.rb
```

I created repository where you can reproduce this bug:
https://github.com/Kroid/zeitwerk-reloading-failed

**Comment by fxn** [comment]
Hi @Kroid.

Reloading deletes constants so that when you refer to them on the next request, their definition is loaded again. However, if you have an instance of the original class stored somewhere, that instance does not change.

This is, schematically, what happens on reload:

```
> joe = User.new
> Object.send(:remove_const, :User) # unloads the constant
> autoload :User, "path/to/user.rb" # sets a Ruby autoload for it again
> alice = User.new                  # the autoload is triggered, User reloaded
```

Now, the key point there is that `joe` is an instance of the _original_ `User` class, and Ruby does not change that. Therefore, the classes of `joe` and `alice` are different. `joe` has a stale one, and `alice` has the current one.

This is what the docs warn about:

> On reloading, client code has to update anything that would otherwise be storing a stale object. For example, if the routing layer of a web framework stores controller class objects or instances in internal structures, on reload it has to refresh them somehow, possibly reevaluating routes.

You don't see the changes in `Router` from taking effect because `config.ru` keeps running, and it passed to `run` an instance of the original router. Rack is storing that original router instance internally, and it is behaving like `joe` above. Reloads do not affect that instance.

To make this setup play well with reloading, you need to add an indirection so that the `Router` constant is evaluated again on a new request. For example, change `call` in `Router` to be a class method (to avoid creating one instance per request), and put this in `config.ru`:

```ruby
require_relative 'app/application'

class App
  def self.call(env)
    Router.call(env)
  end
end

run App
```

Now, Rack stores the class object `App`, which is not reloadable itself, but when `call` is invoked, it is going to evaluate the `Router` constant. If `Router` was unloaded that call will load it again as it happened with `alice` above. See how it goes?

BTW, it would be cleaner to move the auxiliary files `boot.rb` and friends out of the autoload paths, in their own directory, and leave in `app` only what you want to autoload/reload. The traces

```
file .../app/environment.rb is ignored because .../app/environment.rb has precedence
```

hint to that. Those files should not be under a root directory.

**Comment by Kroid** [comment]
@fxn, thanks for the advice! You're right, after this fix in my code, it worked.
