### ISSUE TITLE
Autoloading when .rb file is in a directory of the same name (e.g. component/component.rb)

### ISSUE THREAD

**Issue by ljfc** [fxn/zeitwerk#124]
Hello, thank you for your work on Zeitwerk, it has made our codebase much more pleasant to work with since I heard you talk about it on RubyRogues 😄 

I think the following is currently not possible, and I wanted a) to confirm that it is not possible (perhaps I’m missing some approach using `collapse`, or this can somehow be done with inflection, but I couldn’t see how) and b) ask if this is something you would consider adding to Zeitwerk. I might be able to find time to put in a PR if so, because we’d really like this feature!

For most of our code, the directory structure is as follows:

```
root/
  appname/
    services/
      some_service.rb        => AppName::SomeService
      another_service.rb     => AppName::AnotherService
    controllers/
      homepage_controller.rb => AppName::HomepageController
      signup_controller.rb   => AppName::SignupController
```

This works perfectly with `loader.push_dir ROOT_DIR` and `loader.collapse ['services', 'controllers']`.

However, one part of the code is front-end components, which are kept together with their templates, JS etc, in a folder with the same name as the .rb file:

```
root/
  appname/
    components/
      homepage/
        homepage.rb          => AppName::Homepage
        homepage.html.erb
        homepage.js
 ```

This _can_ be made to work with `collapse` called individually for the `homepage` directory and all the other components, but we have a lot of components and it doesn’t feel DRY to specify them all as collapsed.

Also, some components have sub-components nested inside another subdirectory. For those, we _don’t_ collapse the name of the parent component’s directory. So `appname/components/homepage/welcome_box/welcome_box.rb` defines `AppName::HomePage::WelcomeBox`.

So it seems like perhaps a slightly different rule is needed. Essentially Zeitwerk could be configured to consider directories with exactly the same name as a nested .rb file to collapse, but only when looking for the constant named in _that_ file.

**Comment by fxn** [comment]
No, that is a deviation of the conventions that I do not want to pursue. Reason is it departs from some principles in which Zeitwerk is based that result in an ordered and controlled descend into directories, and their correspondence with the class and module objects that correspond to the namespaces. There's a bit of additional details in [this comment](https://discuss.rubyonrails.org/t/tales-from-an-unconventional-rails-app/75250/11?u=fxn) in the forum.

`collapse` is an API that already deviates a bit, in the sense that namespaces and directories are no longer 1–1, but it was worthwhile in some uses cases, and is still consistent with those principles, because you just jump over those directories and can kind of preserve them. Without any configuration.

### Solution 1: The conventional way

If the project wants to manage loading that code with Zeitwerk, you have to move `homepage.rb` one level up, and do not collapse. With that, the component and subcomponents work normally.

### Solution 2: Roll your own

If you want to have `homepage.rb` there, and still have the namespace for subcomponents, you'd need to roll your own solution, but it would not be too much. Let me explain (off the top of my head):

1. Do not collapse the `homepage` directory.
2. Tell Zeitwerk to ignore `homepage/homepage.rb` early, during the boot process.
3. Setup a `Rails.reloader.to_prepare` callback that manually loads the file `homepage/homepage.rb` using `load` or `require`, dependending on `config.cache_classes`. If `config.cache_classes` is false, you also remove the constant `Homepage` from `Object` before the `load` call (which would in turn invalidate all the child references that belong to subcomponents).

This is based on the fact that when reaching the `homepage` directory, Zeitwerk will detect the constant `Homepage` already exists and will understand it is managed by someone else.

I used "homepage" meaning "any component". If that structure is uniform, I am sure this can be made generic using a glob pattern or simple dir walk and iterate over all top-level components. 

Subcomponents will be in the expected places according to the conventions, and Zeitwerk will manage them just fine, you only need to do that for the top-level ones.

**Comment by fxn** [comment]
I'll keep this one open for now. @pvande has suggested an API for a more generic case that I'd like to explore and maybe could address this.

I'll need some time though.

**Comment by ljfc** [comment]
@fxn thanks for getting back to me so quickly. I absolutely see what you're saying about keeping the simplicity.

For now I'll talk through the options you've suggested with my colleagues and I'm sure we'll land on a good approach. We're not using Rails for this (it's a Sinatra app), so I suppose we should just clean up constants and re-load files in the function where we call `loader.reload` for Zeitwerk?

In the longer run, I'll keep an eye on this in case you decide to take an approach that would allow it. Thanks again.

**Comment by fxn** [comment]
Ah! Cool that you're using Zeitwerk with Sinatra!

Exactly, you need to cleanup the constants when you reload. As you know, `load` loads always. That is what we need. But if the constants are not removed, the classes or modules would get reopened instead of redefined. Relevant specially if you delete stuff in them, like methods.

**Comment by fxn** [comment]
Hey @ljfc, after some exploration, the API remains as it is today. Did you have a chance to discuss the approaches with your colleagues?

**Comment by ljfc** [comment]
Hi @fxn yes we've talked it through and we will move the Ruby files up a level in the fitesystem. It's not a huge loss in terms of things being self-contained, and it means we can carry on using vanilla Zeitwerk, which is working brilliantly for everything else.

**Comment by fxn** [comment]
Brilliant, thanks very much!

**Comment by fxn** [comment]
Hey, I am still thinking about this and have listed a few use cases in #129 to help me see the whole picture. Please feel free to chime in! Would be nice to understand what does `homepage.rb` in your example contain, and how does it relate to the files in the same folder. To better understand your use case.

**Comment by fxn** [comment]
@ljfc I have finally seen more use cases and together with yours helped me come with this feature.

The way it has been designed, there is one special project-wide basename called _nsfile_, instead of a different one per namespace. But it allows having self-contained components.

It's out in version 2.8, and docs are [here](https://github.com/fxn/zeitwerk#explicit-namespaces-defined-in-nsfiles).
