### ISSUE TITLE
Feature Request: Support for `index.rb` files

### ISSUE THREAD

**Issue by marcrohloff** [fxn/zeitwerk#128]
A lot of rails projects I work on have a file structure where the following is repeated in multiple places.
```
.../some_component.rb          # defines SomeComponent
.../some_component/class1.rb   # defines SomeComponent::Class1
.../some_component/class2.rb   # defines SomeComponent::Class2
```
It would be convenient to keep all of the code in a single folder. There are a few benefits.
1) Its easier to understand at a glance
2) In a larger project `some_component.rb` is often completely off the screen in the file browser and it takes a lot of scrolling around
3) It is asier to copy and paste a component or to include using github sub-modules or anything of that sort.

The old Rails loader supports (although not consistently I've found) the following syntax.

```
.../some_component/index.rb    # defines SomeComponent
.../some_component/class1.rb   # defines SomeComponent::Class1
.../some_component/class2.rb   # defines SomeComponent::Class2
```

This is also a style that javascript loaders support (I believe Sass @import also supports something similar)

Is there a way to do this in ZeitWerk that I've missed? Otherwise I think it would be a useful feature to add

**Comment by fxn** [comment]
> The old Rails loader supports (although not consistently I've found) the following syntax.

No, that is not possible unless you manually loaded that index file.

**Comment by marcrohloff** [comment]
I didn't think so which is why I made it a feature request

**Comment by fxn** [comment]
This is a feature request which is similar to https://github.com/fxn/zeitwerk/issues/124.

Is that in the context of a Rails application? Do you need reloading?

**Comment by marcrohloff** [comment]
Yes, without reloading would be too easy.

The issue I see with #124 is if you have a class structure like `Homepage::Homepage` although I guess the same is true in rails where index is a commonly used concept and people might want to implement something like this https://code.tutsplus.com/tutorials/one-class-per-rails-controller-action-with-aldous--cms-23714 

A name like `_index.rb` or `_all.rb` might work better

**Comment by fxn** [comment]
> I didn't think so which is why I made it a feature request

Hmmm, not sure if I understand this answer.

I meant to say the `classic` loader does not support autoloading this index file, so "The old Rails loader supports..." may be a misunderstanding. It would work if you manually load the file somehow (not autoloading).

Let's agree on this one first :).

**Comment by marcrohloff** [comment]
By 'old' I mean it works on a Rails 5.2 project, It might help if it were easier to hook into Zeitwrk in terms of customizing its lookup mechanism

**Comment by fxn** [comment]
There has to be some misunderstanding. The old autoloader does not special-case these index files, they are not autoloadable in the way suggested above.

Maybe you had something special programmed in the app?

**Comment by marcrohloff** [comment]
No we don't do anything explicit. It would be a useful feature nonetheless

**Comment by fxn** [comment]
Can you show me a minimal Rails 5.2 application where Rails autoloads `SomeComponent` from `.../some_component/index.rb`?

**Comment by marcrohloff** [comment]
You are correct. After some debugging this is not a Rails 5 feature. I still think it would be useful to keep components in a single directory in some way instead of always having that one file outside of the directory

**Comment by SampsonCrowley** [comment]
Just want to say, I like `_index.rb` or `_some_component.rb` (where `some_component` is the name of the folder)

an underscore prefix to indicate the "main" module is both an always clear usage, *and* it will always be at the top of the file list

**Comment by fxn** [comment]
Let me think about it.

**Comment by casperisfine** [comment]
I don't know if Zeitwerk should support this, but if I had to add this possibility I'd do it in a generic way that do not impose a new arbitrary convention.

I think this could be done with just a hook when a module is created for a directory.

```ruby
Zeitwerk.on_dir_load = -> (module, path) { require File.join(path, "_index.rb") if File.exists?(File.join(path, "_index.rb")) }
```

Of course I'm not advocating for that particular hooks, there are plenty of alternative API, e.g. hook before creating the placeholder module, after etc etc.

**Comment by fxn** [comment]
I have not taken a decision yet. I believe it is technically possible, but I need to see it written by me and see how it feels.

Off the top of my head, the interface I have in mind goes via configuration:

```ruby
loader.explicit_namespace = nil # default, no stats performed

# Free choice, can be whatever you want, `_index.rb`, `_main.rb`, etc.,
# Must start with an underscore. Files with leading underscores are
# ignored otherwise.
loader.explicit_namespace = "_namespace.rb" 

# foo/_foo.rb convention, where the filename matches exactly the parent
# directory with a leading underscore, no inflection possible.
loader.explicit_namespace = :same
```

But I have to write it and see it.

The argument that made me think was Git submodules. The rest did sound convincing enough to depart from conventions:

* It feels off to define a class or module that represents an entity of you application, say `Hotel` in a dummy file called `_index.rb`.
* Editors can sort explore files alphabetically if you prefer that ordering. Also, fuzzy completion is generally available. And, finally, editors do not influence the design of a Ruby gem like this.
* Careful with flexibility points, Zeitwerk works because it puts strict contraints that make the problem solvable. However, flexibility points create the expectation that you can bend the loader for arbitrary Ruby projects, which definitely it is not the goal of the loader.

**Comment by fxn** [comment]
Gotta simplify that, will play with just one additional convention, which is `foo/_foo.rb`, not configurable. You can define explicit namespaces either way. The `_index.rb` convention does not seem something idiomatic and worth the work and additional configuration point.

**Comment by fxn** [comment]
It has a performance penalty.

Right now, the loader is deliberately lazy to stat as less as possible. But the project could have

```
foo/collapse/collapse/collapse/_foo.rb
foo/collapse/collapse/collapse/bar.rb
foo/baz.rb
```

and the logic to look for the special file needs to do some work in the filesystem. Not liking that approach.

**Comment by marcrohloff** [comment]
> Gotta simplify that, will play with just one additional convention, which is `foo/_foo.rb`, not configurable. You can define explicit namespaces either way. The `_index.rb` convention does not seem something idiomatic and worth the work and additional configuration point.

Having thought about it, it might also make sense to use a filename that couldn't possibly conflict with a legitimate class name line `-index.rb` or `~index.tb`

**Comment by fxn** [comment]
I need to launch the editor yet. But I am leaning on a more normal convention:

```ruby
some_component/some_component.rb
```

to which you need to opt-in, so it is backwards compatible. If you opt-in, then you accept a (probably hard to measure in regular projects) little penalty imposed by looking at collapsed directories if you have any below.

I prefer that convention, because the file would be idiomatically called. If you have an `Admin` explicit namespace, `_index.rb`, `_main.rb`, `-index.rb`, even `_admin.rb` are filenames I dislike, it should have a proper file name, and one named after the class or module, as usual.

So, we'd be supporting two styles for explicit namespaces:

```
hotel.rb
hotel/pricing.rb
```

and

```
hotel/hotel.rb
hotel/pricing.rb
```

However, that's all from the top of my head, imaging usage, how do the file names feel, and if that is technically doable. I need to sit and write it to see if I like it.

**Comment by marcrohloff** [comment]
I also like real filenames but what about class names like `Hotel::Hotel`?

**Comment by fxn** [comment]
Yes, that's a cons. Also, I have to confess that

```
hotel/hotel.rb
hotel/pricing.rb
```

defining `Hotel` and `Hotel::Pricing` hurts my eyes, they are at the same level, they are not distinguishable from each other, but they mean different things.

A special file would convey "I am special". If users can choose, they may pick something that feels good for their taste, which does not need to be the same as mine. I am personally fine with explicit namespaces as they are, as they have been always in Rails, indeed. I am thinking about doing something about this because this is the third time at least that this desire shows up in some form or another.

**Comment by SampsonCrowley** [comment]
> ```
> hotel/hotel.rb
> hotel/pricing.rb
> ```
> 
> defining `Hotel` and `Hotel::Pricing` hurts my eyes, they are at the same level, they are not distinguishable from each other, but they mean different things.

100% agree there, which was why I liked prefixed the prefixed `_index.rb`.

Since it's blatantly against the conventions, it kind of goes along with this unconventional setup; plus underscores mimic "partials" in rails, so feels like a nice balance of unconventional without being completely unprecedented

plus if it's always `_index.rb`, or some other static-but-special naming it should simplify implementation a bit

**Comment by SampsonCrowley** [comment]
or a "hook" like @casperisfine mentioned I think would be an easy way to please everyone. those that stick to the conventions shouldn't notice a dip in performance, those that use a static file name should be able to keep things capable without a huge drag, and those with special needs get their wish without ruining it for the rest of us. nice balance between flexibility and performance

**Comment by fxn** [comment]
Problem with `_index.rb` is that it is so unconventional, that it is just not something you can force users to adapt to.

When people ask for a feature in this line, they generally want to use a file name with the name of the namespace, as in `hotel/hotel.rb`. So, support for this should acknowledge differences in tastes, if technically it is possible. With the configuration drafted above it is fairly simple (mod it is not written), because I can imagine a probe method `lookup` that receives the string configured by the user. In the case of `:same`, at this point Zeitwerk knows which is the namespace and

The hook... could be a possibility, but feels strange because it would be like saying: "As far as I know, this is an implicit namespace and I am about to define it using a dummy module, here you have a callback in which you can run arbitrary code". Does not quite click to me for this feature.

A configuration point could accept a block, though. For example, one that receives the absolute path of a directory, or a constant path for the namespace to be defined, and you are required to return a Ruby file basename ("_index.rb", "main.rb", or a function of the namespace, say). Zeitwerk needs to be always in control of namespace creation, and the API has to put the constraints in place to preserve that.

Something that keeps me thinking is:

* The exact API for this.
* This cannot be all or nothing, for example engines depend on the loader of the parent application which they generally do not control. Therefore, they should be fine shipping explicit namespaces using the current, unique idiom. I believe the lookup should be _in addition to_ the regular way to detect explicit namespaces.
* As always, it is easy to think in the golden path. But you need to think also on strange cases like mixed styles for the same namespace by error in distant places of the project, repeated `_index.rb` files in different directories for the same namespace, etc. I expect extra work/performance cost to detect things like these and act accordingly.

**Comment by fxn** [comment]
> The hook... could be a possibility, but feels strange because it would be like saying: "As far as I know, this is an implicit namespace and I am about to define it using a dummy module, here you have a callback in which you can run arbitrary code". Does not quite click to me for this feature.

Ah, there is another detail. We set a trace point for explicit namespaces, because they may use child constants at the top level in the class or module definition and need to be ready. But if we do not know if a namespace is explicit, that is not in place, and the `require` will err in that use case.

You need strict control over the creation of namespaces for Zeitwerk to work correctly.

**Comment by marcrohloff** [comment]
I think that a structure like hotel/hotel.rb is going to be difficult to implement. If `components/buildings/hotel/hotel.rb` is expected to create a class called `Components::Buildings::Hotel` how do you distinguish it from `components/buildings/house.rb`. Would that create `Components::House` . The logic would have to be fairly intelligent to compare the name with the parent name and, like I said before, that prohiits naming like `Hotel::Hotel`

**Comment by fxn** [comment]
> I think that a structure like hotel/hotel.rb is going to be difficult to implement. If components/buildings/hotel/hotel.rb is expected to create a class called Components::Buildings::Hotel how do you distinguish it from components/buildings/house.rb.

It is doable the way Zeitwerk is implemented. Zeitwerk does a very controlled descend, which is key for the correctness of the library. Basically, if config is `:same`, when Zeitwerk scans and finds the `hotel` directory, it would peek at it to see if it has `hotel.rb` inside (mod collapsing). If it is found, it sets an autoload as it does today, but pointing to that file. Then, when walking the child files and directories of that `hotel` directory, it has to remember that file is not like the other ones.

> The logic would have to be fairly intelligent to compare the name with the parent name and, like I said before, that prohiits naming like Hotel::Hotel

But we do not care, that would be the choice of the user. People wanting _today_ `hotel/hotel.rb` know they pay the price of not being able to define `Hotel::Hotel`. That is fine for them.

**Comment by fxn** [comment]
Let me add that I explained the golden path above. As it often happens, the golden path is 1/N of the implementation. Then you need to work more to account for user mistakes.

**Comment by fxn** [comment]
I have created #129 to have a better perspective on the different feature requests, which may help thinking about this. Let me close here.

**Comment by joelmoss** [comment]
Sorry to raise this again, but I appreciate that this won't be supported in Zeitwerk. But is there a workaround at all?

**Comment by fxn** [comment]
@marcrohloff @joelmoss  This is now supported in version 2.8. You would configure

```ruby
loader.nsfile = 'index.rb'
```

before `setup` are it would just work. Docs with further details [here](https://github.com/fxn/zeitwerk#explicit-namespaces-defined-in-nsfiles).

**Comment by joelmoss** [comment]
Amazing!!!! 👏 Thank you!

**Comment by rc-marc-rohloff** [comment]
wesome, thanks Xavier
