### ISSUE TITLE
Evaluate opening a bit the way to define explicit namespaces

### ISSUE THREAD

**Issue by fxn** [fxn/zeitwerk#129]
## Objective

Some people have asked for other ways to define explicit namespaces. The purpose of this issue is to put together known use cases/feature requests and see if something well aligned with the library is possible.

## Use Case 1

In #124, there's a Sinatra application whose desired layout would be

```
root/
  appname/
    components/
      homepage/
        homepage.rb         => AppName::Homepage
        homepage.html.erb
        homepage.js
        welcome_box/
          welcome_box.rb    => AppName::Homepage::WelcomeBox
```

There, `components` is a collapsed directory.

## Use Case 2

Interestingly, in #128 the use case mentions the word "component" too. There, the feature request is to support one special file in the namespace directory with an arbitrary but fixed name, like `index.rb`:

```
root/
  component/
    index.rb => Component
    foo.rb   => Component::Foo
```

## Use Case 3

In [this post](https://discuss.rubyonrails.org/t/tales-from-an-unconventional-rails-app/75250/3), the missed feature is to be able to define the namespace `FooBar` in

```
projects/foo_bar/config/project.rb
```

## Benefits

* Perceived better code organization in some particular use cases.
* Components can be implemented as Git submodules.
* Easier navigation in editors.

**Comment by fxn** [comment]
@marcrohloff would you mind giving a real example with real names for `component` and `foo.rb`? Is yours a Rails application? 

@pvande would you mind detailing the layout of that project and use a real name for `foo_bar`? Is `config` a root directory? Is yours a Rails application?

**Comment by pvande** [comment]
@fxn Here’s an example of our project’s file structure:

```
/our_rails_app
├── Gemfile
├── Gemfile.lock
├── app
│   ├── assets
│   ├── controllers
│   ├── helpers
│   ├── models
│   └── views
├── bin
├── config
├── db
├── lib
├── log
├── projects
│   ├── k12_science
│   │   ├── assets
│   │   ├── config
│   │   ├── forms
│   │   ├── helpers
│   │   ├── lib
│   │   ├── models
│   │   ├── services
│   │   ├── tasks
│   │   ├── test
│   │   └── views
│   └── k12_math
│       ├── assets
│       ├── config
│       │   ├── locales
│       │   ├── postcss.config.js
│       │   ├── project.rb      (defines `K12Math`)
│       │   └── webpack.js
│       ├── forms
│       │   ├── unit_form.rb    (defines `K12Math::UnitForm`)
│       │   └── lesson_form.rb  (defines `K12Math::LessonForm`)
│       ├── helpers
│       ├── lib
│       ├── models
│       │   ├── unit.rb         (defines `K12Math::Unit`)
│       │   └── lesson.rb       (defines `K12Math::Lesson`)
│       ├── services
│       ├── tasks
│       ├── test
│       └── views
├── public
├── tmp
└── vendor
```
We have Zeitwerk configured with:

``` ruby
    config.autoload_paths << 'projects'
    Rails.autoloaders.each do |loader|
      # Don't autoload from non-code directories
      loader.ignore('projects/*/assets')
      loader.ignore('projects/*/config')
      loader.ignore('projects/*/lib')
      loader.ignore('projects/*/test')
      loader.ignore('projects/*/tasks')
      loader.ignore('projects/*/views')

      # Don't expect project subdirectories (e.g. projects/k12_math/models) to
      # contribute a namespace.
      loader.collapse('projects/*/*')
    end
```

In our application, it would be reasonably straightforward at this point to remove the call to `loader.ignore('projects/*/config')` and write a custom `Inflector` to rewrite files in those project config directories, now that we've established our convention.  This works because a) our convention is regular, and b) our project config directories don't contain other Ruby source (which would have to be selectively ignored or rewritten).  The process of developing that convention would have benefitted from having a simpler way of describing to Zeitwerk that we had one- or two-off files that named specific arbitrary constants.

---

I'm neither of the authors of the first two use cases, but both seem like examples of view components, a la [github/view_component](https://github.com/github/view_component) or [komponent](https://github.com/komposable/komponent).

The current convention in `ViewComponent` is…
```
app/components
├── ...
├── button_component.rb  # Defines "ButtonComponent"
├── button_component.html.erb
├── ...

# or

app/components
├── ...
├── button_component.rb  # Defines "ButtonComponent"
├── button_component
|   ├── button_component.css
|   ├── button_component.html.erb
|   └── button_component.js
├── ...
```

There have been [conversations](https://github.com/rails/rails/pull/36388#issuecomment-498743242) around adopting other conventions as well…  https://github.com/github/view_component/discussions/331 contains a fairly good discussion of desirable code organization conventions and the compromises that were required.

**Comment by marcrohloff** [comment]
> @marcrohloff would you mind giving a real example with real names for `component` and `foo.rb`? Is yours a Rails application?

Ours is a mostly standatd Rails app. One example is

```
app/classes
├── csv_importer
|   ├── output.rb
|   ├── parsing.rb
|   ├── wrapper.rb
|   └── options.rb
└── csv_importer.rb
```
Its the last file that I would prefer to move into the `cvs_importer` folder

**Comment by fxn** [comment]
I've tweeted about this, but no people have joined the conversation or have shown more use cases. 

It's a small set of use cases, and I'd say the 3rd one is slightly different, it is a more generic "let me define constants in arbitrary files".

I suspect defining namespaces that way is a niche need and generally people are fine with the current convention, which has been the only one available in Rails for +15 years indeed.

In the case of Git submodules or `path` dependencies, I am sure you can make it work in a way or another, collapsing if needed.

By now, I am not going to close the issue, but I do not feel strongly convinced this is worth the work and additional logic inside the gem. Zeitwerk performs a very controlled descend in the root directories, the mental model and implementation are easy to reason about and clean, in a tricky problem. I'd change this only if it is really justified.

I'll wait a bit more.

**Comment by ljfc** [comment]
@fxn Here is a little more detail about my use-case, although honestly I tend to agree that this isn’t vital. It’s working perfectly well with `component.rb` lifted up one level to be alongside `component/`.

```
app # Everything inside here is within the App module
├── Gemfile
├── Gemfile.lock
├── app.rb
├── components # These are shared components that do not belong to a specific page. “Components” is not a module.
│   └── layout # Subfolders *are* modules.
│       ├── default
│       │   └── default.erb # ERB template rendered by App::Layout::Default
│       └── default.rb # Defines App::Layout::Default, a component class
├── config.ru
├── controllers # Again, not a namespace because classes are expected to be called SomethingController
│   ├── base_controller.rb # App::BaseController
│   ├── error_controller.rb # App::ErrorController
│   ├── homepage_controller.rb # App::HomepageController
│   ├── signup_controller.rb # App::SignupController
├── pages # These are essentially the same as components, except that they relate only to a single page.
│   ├── homepage
│   │   └── homepage.erb # ERB template rendered by App::Homepage
│   ├── homepage.rb # Defines App::Homepage, a page component class
│   └── signup # Namespace module for page components that render routes from App::SignupController
│       ├── details_page
│       │   ├── child_details
│       │   │   └── child_details.erb
│       │   ├── child_details.rb # App::Signup::DetailsPage::ChildDetails subcomponent
│       │   ├── details_page.erb # ERB template rendered by App::Signup::DetailsPage
│       │   ├── name_and_email
│       │   │   └── name_and_email.erb
│       │   └── name_and_email.rb App::Signup::DetailsPage::NameAndEmail subcomponent
│       └── details_page.rb # App::Signup::DetailsPage
├── services # There’s all sorts of stuff in here, I include part of it for completeness on what a ‘component’ actually is.
│   ├── component
│   │   └── page.rb # App::Component::Page base class for page components
│   ├── component.rb # App::Component base class for generic components
│   └── page_helper.rb # Sinatra mixin for rendering a Component::Page
```

The idea is that all rendering is done by subclasses of `App::Component`, which is a fairly simple object that uses Tilt to render an ERB file in the context of an instance of itself. So a subclass can define whatever parameters and methods the ERB template needs.

Any `App::Component` can also render another `App::Component` from ERB i.e. a subcomponent.

This lets us then split up chunks of logic and template in whatever way we feel makes most sense.

There is a slight specialisation of `App::Component` in `App::Component::Page`, which allows it as root rendering object to tie in with Sinatra via a helper, but that’s not really important here.

The important thing is that pages are allowed to have subcomponents which relate _only_ to them, which then exist in subfolders of the page component. The idea here is that whether a page is something very simple or something hugely complex, you always know a) where you are in the hierarchy of pieces that make it up and b) whether a given component is something that only relates to that page, or is shared with other pages.

In answer to you specific question on #124, `homepage.rb` contains something roughly like this:

```
module App
  class Homepage < Component::Page

    def template_file
      File.join __dir__, 'homepage', 'homepage.erb'
    end

    def title
      'Welcome'
    end
end
```

And renders an ERB template something like this:

```
<%|= component Layout::Default, title: title do %>
  <body>
    <h1><%= title %></h1>
    <!-- More homepage content -->
  </body>
<%| end %>
```

There’s quite a lot going on here, so I’m happy to explain further if you have more questions. But the key thing that Zeitwerk provides is that it’s trivial for a developer to add a component to a template with a line like `<%|= component Namespace::Widget param: :value %>` without worrying about making sure other parts of the code know about it. `App::Homepage` doesn’t have to know that its ERB template uses `Layout::Default`.

But this works with the file structure above! So as I said I’m not sure this is a serious need for us. You can see in `pages/signup/details_page` above that the structure is arguably made a little messier because `details_page.rb` ends up some distance from `details_page/details_page.erb` depending on how much other stuff is in `details_page/...`. For that reason it might be nice if the Ruby files could sit alongside their ERB templates. (N.B. The full file structure is busier than this because there’s also CSS, JS and YAML files in some of the components). But it’s only a very mild cognitive overhead for something that is still very logical.

**Comment by fxn** [comment]
Hi,

I have asked for as many feedback as possible in different channels to understand use cases and demand.

Zeitwerk does not aim to be a generic loader for arbitrary Ruby projects. Ruby is very flexible, Zeitwerk sets strict constraints to make the problem solvable, to offer a contract that is easy to reason about, to bring some uniformity to code bases that make them predictable as they are in Rails, etc.

I have been open to add some flexibility to the original contract up to some point. When Zeitwerk was published you had the inflector as unique flexibility point. Later on, collapsing was added. Recently, in 2.4.0, you can assign an already existing, non-reloadable namespace to a root directory.

It's a fine balance, I have to sense it is absolutely justified, I have to feel it is coherent with the vision I have for the library, and I have to somehow imagine how could a change in the contract influence its future, which expectations could create to stretch the contract even further in just this new and slightly different direction, whether the added code is worthwhile, etc.

After thinking about it for a few weeks, and listening to the use cases, I am definitely not inclined to explore this further as of today. (I say "explore", because you still need to synthetize an API from the use cases, which is not obvious.)

Thanks all for participating in the thread.

**Comment by fxn** [comment]
The property that Zeitwerk has kept preserving is that the project tree agrees with the constants hierarchy. If you have `Foo` and `Foo::Bar` and they have files, `foo.rb` is necessarily higher than `bar.rb` in the file system.

It is easy to reason about, and the implementation reflects that in a controlled and easy to undestand descend (mod edge cases).

if for organizational purposes you like some intermediate folders, collapse allows you to do that. if `Foo`, like `Object`, already existed, you can set your root there.  But the relative order is preserved by the contract.

**Comment by joelmoss** [comment]
@fxn as requested at https://x.com/fxn/status/1826918015234973983?s=61...

So my use case is one that is popular in the JavaScript world, and seems to be the same as use case 2...

```
app/
  components/
    list/
      index.rb        => Class(Components::List)
      item.rb          => Class(Components::List::Item)
```

So the directory `app/components/list` contains an `index.rb`, so when calling `Components::List`, it is `app/components/list/index.rb` that is loaded.

But if `app/components/list.rb` exists, then that would take precedence and would be loaded instead, as it comes first in the file system hierarchy.

Note that the index would only be loaded if it exists, which may not be so obvious. If it doesn't exist, then standard behaviour is observed.

Any other files within the `app/components/list` directory would be used and loaded as normal, ie. `app/components/list/item.rb` would be `Components::List::Item`.

So from what I can see, and from my naive POV, it is the `index.rb` that is the only change in behaviour here.

Hope this helps describe my use case.

**Comment by fxn** [comment]
Thanks @joelmoss. Could you try to verbalize why would you like to have this?

Because, you know, the fact that JavaScript has that pattern is not very relevant for Ruby, we do not design things to imitate patterns from other programming languages.

**Comment by joelmoss** [comment]
Fair point 😆

I'm primarily coming from a component POV, and I'll use some examples of actual components that I have created and use regularly.

### Single file components

In the simplest of cases, a component is made up of just one file - easy peasy...

```
app/components/
  one.rb => Components::One
  two.rb => Components::Two
  three.rb => Components::Three
```

### Multi file components

But usually a component is made up of a main component file, and several children, or sub components that the main component would use. So it makes sense that these are all located within the same directory, which is named after the main component.

```
app/components/
  table/
    component.rb => Components::Table::Component
    cell.rb => Components::Table::Cell
    header.rb => Components::Table::Header
    footer.rb => Components::Table::Footer
```

The annoyance with this is that the `Component` suffix of `Components::Table::Component` is somewhat redundant here, as we know it is a component. And it makes component names longer than needed.

Even though this is inspired by JS conventions, I believe that it is easily applied to Ruby, and would be very useful. The simple conveniance of calling `render Components::Table`, instead of `render Components::Table::Component` would be really, really nice.

**Comment by fxn** [comment]
For the archives, this is now supported in version 2.8.
