### ISSUE TITLE
Advice on auto loading 3rd party gems?

### ISSUE THREAD

**Issue by will** [fxn/zeitwerk#136]
Hi, thanks for Zeitwerk, I've been using it now for a while in a non-rails project, and it's been great.

I unfortunately use some gems that are very large and slow (2+ seconds) to load. Zeitwerk has already helped a lot in that if I don’t touch a class that uses these gems, development startup and individual tests are nice and fast. However I've noticed that even in the classes that require these gems, only a couple of methods actually need them. 

I just tried out creating a "gem stubs" directory with files named after the gems (and sub directories with namespaces that some of them have). The ruby files only do a `requre "gemname"`. This seems to work great, and now I can put off loading these awful dependencies in dev&test unless I really need to.

Some questions about this though:

1. Am I missing anything that would make doing this a big disaster later?
2. Is there any way to skip the façade of creating mostly empty files, and instead tell Zeitwerk directly what require to do for a gem?
  a. if not right now, is this something that you would consider adding, or accept a PR that adds it?

**Comment by fxn** [comment]
Hi! Let me ask a couple of initial questions:

1. Do you control these gems?
2. Do they eager load?

**Comment by will** [comment]
I don’t control them. (They are the various aws sdk gems, which are large but not awfully large, and the azure sdk gems which contain generated copies of every minor api bumps resulting in hundreds of megabytes of duplicated code of which you only ever need maybe 10MB). 

I'm not sure exactly what you mean in 2. They don’t use Zeitwerk themselves. In production I call `Zeitwerk::Loader.eager_load_all` right now and that's been working well

Also if this ends up working well, it'd be kind of nice to not need any manual requires in application code, except for maybe some ruby stdlib things.

**Comment by fxn** [comment]
Gotcha.

Why do those gems take so long to load? Do their entry points eager load them in practice? A gem eager loads itself if the entry point has a series of `require` calls, or it has a bunch of `require` calls, whose required files have more `require` calls, doing an eager load effectively.

That is what I'd like to understand first.

**Comment by casperisfine** [comment]
I'd have another question: do you have bootsnap enabled?

**Comment by will** [comment]
The azure network sdk gem for example has a ton of almost-redudant copies of itself: https://github.com/Azure/azure-sdk-for-ruby/tree/master/management/azure_mgmt_network/lib and it continues to grow several times a year.

At first when looking in there, I noticed they used `autoload` so I figured I could be smart and just load the latest profile, however it eventually goes back and requires the whole project https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_network/lib/profiles/latest/modules/network_profile_module.rb#L5 

```
ruby -rbenchmark -e 'p Benchmark.measure { require "azure_mgmt_network" }.real'
1.022731000004569
```

and @casperisfine, I do use bootsnap, it brings it down a little but still a long time to just require a gem, 
```
ruby -rbenchmark -r./config/bootsnap -e 'p Benchmark.measure { require "azure_mgmt_network" }.real'
0.4448180000035791
```
especially when running a single spec, where half a second could easily double the time. And really my main motivation is getting single specs to be super fast, as well as starting development interactive consoles, so if a spec doesn't actually touch this azure sdk not loading it would be really good.

https://github.com/Azure/azure-sdk-for-ruby/issues/2060 has some more information. At the end there I found someone at Chef who forked the gem to remove the hundreds of megabytes of code, but actually using that fork for a gem I don’t control is difficult. Simply using the git and glob options in bundler didn't reliably, nor did building the gems and vendoring them for reasons not really in the scope here

**Comment by fxn** [comment]
## What I have understood

Let me first write what I have understood:

Let's go back for a moment to the point in which the project was not using the "stubs". Some classes depend on those gems, and others don't. Only the classes that depend on those gems load them:

```ruby
require "heavy_gem"

class C
  def foo
    Heavy::Gem.new
  end

  def bar
    Heavy::Gem.new
  end

  def baz
    # Does not use the heavy gem.
  end
end
```

So, tests not passing through `C` are fast because the project autoloads, but as soon as you hit `C` you load the heavy gem as a side-effect even if only `baz` is executed.

In order to make that even more lazy, the project has some stubs like `lib/heavy/gem.rb` that basically perform `require` calls.

## My feedback

If the description above is good, I'd advice against doing it like that. The golden rule is that every project is responsible for loading and defining its classes and modules. Your interface to that "system" is `require`, the gem tells you which is the entry point or points, and you `require` them, and the gem does internally whatever is needed. That is opaque.

In this case, the main problem is in the namespace: If you define the stub, Zeitwerk is defining a dummy module for you. But you do not control the definition of that module, it should be totally deferred to the original gem. If the namespace was a class, you should load the class first to reopen, defeating the whole purpose.

On the other hand, if you reload, the `require` call won't be executed again because it is idempotent.

Reloading could be problematic also (don't know if your project reloads).

Careful also with relative paths that are equal in different directories of `$LOAD_PATH`, because Ruby only loads the first occurrence of them if the `require` call uses a relative path.

Options:

1) Conclude that 2 seconds is not that terrible given it is out of your control and only happens if you hit `C`.

2) Move the `require` call inside the two methods. This would be the clean Ruby-way. If it was my project, I'd add a comment saying "We delay loading this because it is costly, see <link to issue>." So, you trade doing things a bit custom for speed. Trade-offs!

3) Use Zeitwerk as a way to automate those `require` calls.

OK, while 3) may technically work by luck, that is not a natural way to use Zeitwerk, it involves extra files, takes risks, etc. I'd personally go with 1) or 2).

So, that is my feedback. Of course, it is your project, so your call, you are better informed now to take a decision :).

> Is there any way to skip the façade of creating mostly empty files, and instead tell Zeitwerk directly what require to do for a gem?
a. if not right now, is this something that you would consider adding, or accept a PR that adds it?

No, definitely not something Zeitwerk would address.

**Comment by will** [comment]
Thank you for taking the time to understand my problem and give advice. I'm not sure exactly which path I'll take, but I appreciate it a lot.

I'll close this now since I know you like to keep the trackers at 0 :)

**Comment by adam12** [comment]
>     2\. Move the `require` call inside the two methods. This would be the clean Ruby-way. If it was my project, I'd add a comment saying "We delay loading this because it is costly, see (link to issue)." So, you trade doing things a bit custom for speed. Trade-offs!

I do this in a project with these exact Azure dependencies, FWIW.
