### ISSUE TITLE
on_load with support for a glob pattern

### ISSUE THREAD

**Issue by solnic** [fxn/zeitwerk#164]
Hey there!

This is a follow up after https://twitter.com/fxn/status/1401917199804157954?s=20

Context: I'm refactoring rom-rb's "auto register" feature which is responsible for eager-loading all files that define user's component classes that will be used at runtime. It needs to load the files and actually detect which class constants are available. I'm porting this to use Zeitwerk and most of the functionality already works so this is great.

I noticed that there's `on_load` callback which currently accepts name of a constant as a string. I thought about using it but then I realized I don't actually know the name of the constant upfront, but I do know the top-level namespace. This made me think that if Zeitwerk supported a simple glob pattern, ie `on_load("Persistence::Relations::*")` then I could drastically simplify my code by removing constant inference part. Alternatively, it could also be a separate method like `on_namespace_load("Persistence::Relations")` which yields when all files from that namespace have been loaded.

I'm not sure if this is a feasible thing to do from Zeitwerk POV, but since it most likely knows about constants internally, then maybe it is 🙂 

Thanks!

**Comment by casperisfine** [comment]
What about:

```ruby
loader.on_load do |mod|
  if mod.name.start_with("Persistence::Relations::")
    # your thing
  end
end
```

**Comment by solnic** [comment]
@casperisfine actually that was literally the first thing I tried 🙂

**Comment by fxn** [comment]
Let me think a bit about it.

The interface generic `on_load` callback without argument didn't seem a good fit to me, because the use cases I can imagine look for specific classes. So, you'd need to write

```ruby
loader.on_load do |mod|
  case mod.name
  when "Foo"
    # Do this
  when "Bar"
    # Do that
  end
end
```

And I do not like that code. If the common case is to look for certain patterns, then the interface that is more natural to me is to pass the pattern, and be called only if it matches. That is, please take care of the dispatch yourself, call me only if need it.

So, on a first thought, I believe I'd be more inclined to accept glob patterns and/or regular expressions. In the rare case that you want to be called for everything, then you could configure "*".

**Comment by casperisfine** [comment]
> because the use cases I can imagine look for specific classes.

You might want to match on things other than name though, e.g.:

```ruby
loader.on_load do |mod|
  if mod < ActiveRecord::Base
    # blah
  end
end
```

In theory accepting a glob pattern could allow a sligthly faster dispatch for this specific use case, but ultimately my humble opinion is that it's better to leave the dispatch and filtering to the callee as it's more flexible and less maintenance for Zeitwerk. But as always it's your call.

**Comment by fxn** [comment]
@casperisfine yeah, those are good points.

It would also leave to the user which is the most efficient way to check things, like `start_with?`, `fnmatch?`, `match?`, `=~` to get captures, .... If we do "*" then we have to `fnmatch?` ourselves, and then the block would dispatch again.

Also, now we have a hash table to know if there are any callbacks for a given loaded class/module, but pattern lookup would be O(n), which is not important for small n, but makes you think.

In this option, we could keep class names for backwards compat and for the use cases that are like the one in the README, and the catch-all callback for anything else.

In case both are present, natural order could be more specific first, and then the generic one.

**Comment by casperisfine** [comment]
> Also, now we have a hash table to know if there are any callbacks for a given loaded class/module, but pattern lookup would be O(n), which is not important for small n, but makes you think.

Exactly. It make sense to provide a specific API for exact match, as it's a very common use case and brings a significant perf improvement (because it's just one hash lookup). 

As soon as you introduce some kind of matching, be it `fnmatch?` or even a Regexp, that will be very hard to optimize anyway, and I fear we might wish we didn't do it some time down the line.

> In this option, we could keep class names for backwards compat and for the use cases that are like the one in the README

Even without backward compat, I think the exact match would still make sense because:

  - It's super easy to implement for Zeitwerk anyway, and "uncontroversial". e.g. very little chance you get some issues of people being confused by the behavior.
  - It's a very common use case, if not the most common.
  - It's much more efficient. If your app load 10k constants but you want a callback for only one, 10k hash lookups are much cheaper than 10k proc calls.

At least with such "unscoped" callback, it's up to the user to have a fast matcher in there to not slow things down.

**Comment by fxn** [comment]
@solnic done! Would be included in the forthcoming 2.5. 

For symmetry, specific callbacks get also the loaded object as a block argument.

Regarding a release, my idea is to wait until I finish the deletion of `classic` mode in `rails/main`. Just in case that work shows it would be nice to have something else in 2.5. @solnic do you plan to ship your refactor soon?

**Comment by fxn** [comment]
Wait a minute, after sleeping on it, I see the callback needs also the constant path. Reason is, while the most common case for autoloading is classes and modules and documentation [deliberately](https://github.com/fxn/zeitwerk/blob/main/PROJECT_RULES.md#documentation) focuses on that to ease the terminology, the loader is only concerned with constants.

That is, the loader supports

```ruby
# x.rb
X = 1
```

one common case is

```ruby
# lib/foo/version.rb
module Foo
  VERSION = "1.2.3"
end
```

If you get passed 1, or "1.2.3", you don't know what was loaded.

I'll work on that later.

**Comment by fxn** [comment]
Done in https://github.com/fxn/zeitwerk/commit/ea46b207434c9ec3404ac18be870eb676914b870.

**Comment by solnic** [comment]
@fxn it works!!! thank you, this is so helpful! ❤️ What an amazing turn of events!
