### ISSUE TITLE
Best practices for scalar constants?

### ISSUE THREAD

**Issue by nkeyes** [fxn/zeitwerk#166]
What is the best practice for when you want to define multiple scalar constants in a in a module?

Traditionally, I would do something like this: 
```Ruby
# pretend Ruby doesn't already have a Math module
module Math
  TAU = 6.283185307179586
  PI = TAU / 2
  E = 2.718281828459045
  PHI = 1.618033988749894
end
```
The only guidance I've found on this so far is dealing with `SomeGem::VERSION`.

As far as I can tell, Zeitwork expects you to define each of those in their own file and customize the inflector for each. That works for one-offs like `SomeGem::VERSION`, but does not scale.

Am I missing something?

**Comment by nkeyes** [comment]
Eager loading "solves" this, but that is less than ideal for testing, especially in a larger Rails app.

**Comment by fxn** [comment]
Oh, the file name conventions are only relevant when the constant is defined in its own file, as in `lib/my_gem/version.rb`. There, you need the inflector.

But an autoloadable class or module may define nested constants arbitrarily in its class or module body. If you define `Math` like that and refer to `Math::E`, then Zeitwerk will autoload `Math`, and when the evaluation of the file is done, `Math::E` exists and all works as expected.

So, best practice is to do it like in regular Ruby, as in your example.

**Comment by fxn** [comment]
Let me stress that `Math::E` is treated by Ruby as a compound expression, it is not a single unit as in other languages with syntax for types.

For Ruby, `Math::E` means "Get a class or module whose name is `Math` first. Then, look for a constant called `E` in that object".

So the first expression evaluated is `Math`. That returns a module, and then Ruby performs a constant lookup on that module. Since `math.rb` defines both `Math` and `Math::E`, when `Math` is loaded, we are ready for the second step.

**Comment by nkeyes** [comment]
@fxn Thanks, that makes sense.
Upon further digging, the issue I ran into actually seems to be a circular dependency between constants

**Comment by fxn** [comment]
I have added documentation about this in https://github.com/fxn/zeitwerk/commit/9b87169d306913c402d156f7e4f89f4c49c7133e.
