### ISSUE TITLE
Unable to find file (Zeitwerk::NameError)

### ISSUE THREAD

**Issue by lexdubyna** [fxn/zeitwerk#176]
Hello
I am trying to use Zeitwerk with a sinatra app and for some reason the autoloading doesn't work as expected.
Here is the file structure:
```
|── app
│   ├── controllers
│       └── application_controller.rb
│   ├── middleware
│       └── authenticator.rb
|── lib
├── autoload.rb
├── config.ru
└── README.md
```

application_controller.rb:
```
require 'sinatra'

class ApplicationController < Sinatra::Base
  use Middleware::Authenticator

  get '/' do
    'Hello world!'
  end
end
```

autoload.rb:
```
require 'zeitwerk'

loader = Zeitwerk::Loader.new
loader.push_dir("#{__dir__}/app")
loader.push_dir("#{__dir__}/lib")
loader.setup
```
the error that I am getting:
```
/usr/local/bundle/gems/zeitwerk-2.4.2/lib/zeitwerk/loader/callbacks.rb:18:in `on_file_autoloaded': 
expected file /app/app/middleware/authenticator.rb to define constant Middleware::Authenticator, but didn't (Zeitwerk::NameError)
```
Why is it looking for the file in `app/app`?
Please help.

**Comment by casperisfine** [comment]
> Why is it looking for the file in `app/app`?

I presume you are on heroku? On Heroku your repository is copied in `/app`, so even Rails apps have `/app/app`, it's no big deal at all.

It's much more likely that your problem is `app/middleware/authenticator.rb` I presume the constant in that file isn't namespaces by `Middleware`.

**Comment by fxn** [comment]
And... does the file define the constant?

**Comment by lexdubyna** [comment]
app/middleware/authenticator.rb defines `class Authenticator` and it is not namespaced by `Middleware`.
Maybe I am getting it wrong, but my `config.ru` loads `Controllers::ApplicationController` with `ApplicationController` class not having any namespace. I had the impression that Zeitwerk allows you not to define namespaces as they are configured by the folders structure.

**Comment by fxn** [comment]
Not really.

With your configuration, `app/controllers/application_controller.rb` should define `Controllers::ApplicationController`. The file starts to be evaluated, but that fails in the middle of it because `Middleware::Authenticator` is not found in `use Middleware::Authenticator`.  Otherwise, you'd get an error about `Controllers::ApplicationController` too, because the file does not define it.

Similarly, `app/middleware/authenticator.rb` should define `Middleware::Authenticator`. Indeed, the line `use Middleware::Authenticator` is correct, it uses the namespace.

In Rails applications, `app` is not in the autoload paths by default, but `app/controllers` is, that's why you don't need namespaces for controllers.

Please check the [documentation](https://github.com/fxn/zeitwerk#file-structure) about project layout for further details.

**Comment by lexdubyna** [comment]
@fxn Thank you for clarification!
My mistake, fixed it, all working now.
