### ISSUE TITLE
Question re Rails’ config.autoload_once_paths

### ISSUE THREAD

**Issue by ngan** [fxn/zeitwerk#187]
Hey @fxn, thanks for Zeitwerk. I noticed Rails 7 updated its doc to mention `config.autoload_once_paths` without a [“this is discouraged nowadays” notice](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#rails-autoloaders). Then I thought it’d be _somewhat_ interesting to make the `lib` directory an autoload once path. Why? Here’s some (debatably small) advantages:
- I work in a large monolith touched by 100s of devs with varying degree of Ruby/Rails knowledge and conventions. One confusion is when to `require` and when not to `require`. Doing this would take the `require` pretty much out of the equation.
- Eliminates extra, unneeded `require`s that might (pre)load parts of the app prematurely in dev/test.
- Today, you have to know 2 facts when using `lib`: (1) It must be `require`d and (2) it does not get reloaded. This change/convention would get rid of the first must-know.

So I added `lib` to `config.autoload_once_paths` and the app failed to boot. After some digging, I realized the “problem” was that Rails actually has 2 Zeitwerk loaders (main and once). If I have something like this, things would break:

- `app/models/events/foo.rb`
- `app/services/events/bar.rb`
- `lib/events/foo.rb`

I believe `Events` gets autovivified by the existence of the `lib/events` directory. When you call `Events::Foo` or `Events::Bar`, it would say it’s not found. I think this is because the `once` loader claims knowledge of `Events` and the search stops there. This is a simplified version of my setup so let me know if this doesn’t reproduce my problem. I can provide more details. If you don’t add `lib` to autoload once, then `Events::Foo` and `Events::Bar` can be found since they live in the same Loader even though they have different paths (`models/events` and `services/events`).

**Comment by fxn** [comment]
Hi @ngan,

The `lib` directory was in the autoload paths by default up to Rails 3. It was removed because it proved to be too problematic because it mixes regular code with Rake tasks, templates, etc.

In the case of Zeitwerk, if you add `lib` to any of the autoload paths (regular or once), then you need to tell the autoloader to ignore folders like `lib/tasks`, because otherwise the configuration is telling that is a namespace `Tasks`, and you'll find it in `Object.constants`.

The rule for using `require` is simple: You _never_ use `require` for autoloadable code. And you use it for everything else. You _never_ `require "user"`, but you `require "nokogiri"`, so to speak. In `classic` mode, the problems derived from using  `require` where documented [here](https://guides.rubyonrails.org/v6.1/autoloading_and_reloading_constants_classic_mode.html#autoloading-and-require).

Even if you added `lib` to the autoload paths, people need to know anyway.

Nowadays, the recommendation is: If you have stuff to reload that that is suitable for a `lib` directory, just throw it into `app/lib`.

Regarding the `Events` namespace, the application has `Events::Foo` defined in two places? Or are those two `foo.rb` a collapse only in the example? As I said, the modern recommendation is to put these things into `app/lib`, but I'd like to understand that behavior anyway.

**Comment by ngan** [comment]
Unsurprising, I screwed my example 😓 it was too early in the morning. It should be `lib/events/something_else.rb`. I just wanted to point out the collision of `Events` between the two loaders. Let’s throw out my `lib/` example, and go with your `app/lib` example.

I can understand all your points about autoloading `lib`. We’ll use `app/lib` and add it to autoload_once_paths. This way, I get an autoloaded path that I can then reference constants defined there in initializers. This basically mirrors the example in the 7.0 docs (`app/serializers`).

I believe this still brings up the problem if you had:
- `app/models/events/foo.rb`
- `app/lib/events/bar.rb`

You can’t access `Events::Foo`.

> BTW, I believe I may take your feedback to improve the documentation.

❤️

**Comment by fxn** [comment]
@ngan by far, the main use case for Zeitwerk is project trees that are managed uniformly and have no overlap with other project trees.

**Comment by ngan** [comment]
Very good points! Going to close this issue out. Always a pleasure to have discussions with you, @fxn!
