### ISSUE TITLE
Support for concerns directories in subdirectories?

### ISSUE THREAD

**Issue by leoarnold** [fxn/zeitwerk#190]
I have a Rails 6 app and would like to define `Acme::DataWarehouse::Mungeable` in

```
app/acme/data_warehouse/concerns/mungeable.rb
```

rather than

```
app/acme/data_warehouse/mungeable.rb
```

in order to fall in line with Rails code organization patterns. Is this supported?

**Comment by fxn** [comment]
Hmmm, technically, that is possible.

However, before giving you the solution, let me warn that is _not_ a common Rails pattern. The standard patterns in Rails are:

1. `app/models/foo.rb` defines `Foo`, not `Models::Foo`.
2. `app/models/concerns/bar.rb` defines `Bar`, not `Models::Bar` or `Concerns::Bar`.
3. `app/models/woo/concerns/woo.rb` has not special meaning, it should define `Woo::Concerns::Woo`.

The reason is that `app/models/concerns` is a directory for reusable concerns. Regular mixins cooexist with the rest of the files with no special "concerns" folder. That is, if you extract the logic for `Pricing` in `Hotel`:

```ruby
class Hotel <ApplicationModel
  include Pricing
end
```

and that `Hotel::Pricing` is not reusable, but is just part of the implementation of `Hotel`, you store it in `app/models/hotel/pricing.rb`, simple.

As you see, your structure deviates quite a bit, and that could confuse other or future team members.

Do you still want the solution?

**Comment by leoarnold** [comment]
@fxn If you call it a bad idea, then it must be one :wink:
