### ISSUE TITLE
How to work for edge case which exists more than one same name constant defined.

### ISSUE THREAD

**Issue by zw963** [fxn/zeitwerk#193]
[this](https://github.com/zw963/test_zeitwerk) is a sample project for describe this issue.

const "App" defined on `app/app.rb` and `helpers/app.rb`, with #foo, #bar method defined individually.

When i add both of them with push_dir.

I found only #foo is get defined when i load this project.

![image](https://user-images.githubusercontent.com/549126/140614767-70210fd4-e8a0-4293-8948-1fb6cc4c3c69.png)

So, i am curious, how zeitwork work when meet this case.

Thank you.

**Comment by fxn** [comment]
That is unsupported.

In Ruby, if you have two `foo.rb` in `$LOAD_PATH` and you `require "foo"`, only the first one is loaded. Zeitwerk emulates Ruby, if you have two `app.rb` in the root directories, only the first one is taken into account. If you enable logs, you'll see the second one is logged as being shadowed by the first one.

So, you need to roll your own. For example, one way to do what you want is add this at the bottom of `app/app.rb`:

```ruby
load "#{__dir__}/../helpers/app.rb"
```

The example uses load because if you have reloading enabled, you want a reload of `App` to evaluate that other file again. If reloading is disabled, it can be `require`.

**Comment by fxn** [comment]
Another option is to define `app/helpers/app/helpers.rb`, and then include that module in `App`:

```ruby
# app/app.rb
class App
  include Helpers
end

# app/helpers/app/helpers.rb
module App::Helpers
  ...
end
```

This one is more aligned with Zeitwerk, the previous one is a contorted usage in a project that deviates a bit from the conventions.

**Comment by zw963** [comment]
Thanks for excellent explain!
