### ISSUE TITLE
Namespaced module is getting ignored by Zeitwerk

### ISSUE THREAD

**Issue by roooodcastro** [fxn/zeitwerk#197]
Hi, I have an existing large Rails app, and I'm having difficulties making it correctly load a module. I have the following directory structure (only listing stuff relevant for this namespace):

    ├ app
    │ └ models
    │   └ feeds
    │     ├ providerip.rb
    │     ├ providerip/class1.rb
    │     └ providerip/class2.rb
    └ lib
      └ feeds
        └ providerip
          ├ class3.rb
          └ class4.rb

The `app/models/feeds/providerip.rb` module has this:

    module Feeds
      module ProviderIP
        class << self

          def config
            @config ||= Rails.application.config_for(:providerip)
          end
        end
      end
    end

And `ProviderIP` has an entry in the inflections file as it ends with an acronym. I've tested naming the files and directories both as `provider_ip` and `providerip`, and only the latter seems to work:

    inflect.acronym 'ProviderIP'

When I run the app locally, everything works, however on staging/production I'm getting the error `undefined method :config for Feeds::ProviderIP`. If I open a Rails console in one of these environments, and run `Feeds::ProviderIP.methods`, I cannot see `config` listed there, which means it's not being loaded.

I've added `Rails.autoloaders.log!` to `application.rb` just after `config.load_defaults 6.1` on my staging environment, and I noticed these lines in the Zeitwerk logs (among hundreds of other lines) when I run `rails console`:

    Zeitwerk@rails.main: the namespace Feeds already exists, descending into /repos/app/releases/20211210164808Z/app/models/feeds
    Zeitwerk@rails.main: file /repos/app/releases/20211210164808Z/app/models/feeds/providerip.rb is ignored because Feeds::ProviderIP is already defined

This seems to mean that Zeitwerk is not even trying to load the module, but I'm not sure why. I'm also not sure where it is finding an existing `Feeds` reference, since these two lines are the first in the log that references either `Feeds` or `ProviderIP`, and no other lines in `application.rb` load anything that references it.

Also, `Feeds` namespace is the real namespace name, but `ProviderIP` is made-up for this issue, I can't divulge the real name but it's a specific enough name that I'm 100% sure no other gems or parts of the code have any name clashes with it. So it's possible that a gem has a `Feeds` namespace, IDK, but I'm sure that `Feeds::ProviderIP` does not show up before that point in the Zeitwerk log, and even if it did, this is what I get in my development environment, which is the behaviour I was expecting:

    Zeitwerk@rails.main: module Feeds autovivified from directory /Users/razevedo/dev/repos/myrepo/app/models/feeds
    Zeitwerk@rails.main: autoload set for Feeds::ProviderIP, to be autovivified from /Users/razevedo/dev/repos/myrepo/app/models/feeds/providerip
    Zeitwerk@rails.main: earlier autoload for Feeds::ProviderIP discarded, it is actually an explicit namespace defined in /Users/razevedo/dev/repos/myrepo/app/models/feeds/providerip.rb

What's going on here? I feel the `inflection.acronym` entry has something to do with it, but I'm not sure how to get around it. I'm using Rails 6.1 and Ruby 3.0.

**Comment by fxn** [comment]
I believe there's two separate things going on here. One is the unexpected presence of `Fleets` when the loader scans the project tree, and another one is the inflection. Let's go one by one.

First, is `lib` in the autoload paths? You can test with

```
bin/rails runner 'pp ActiveSupport::Depedencies.autoload_paths'
```

If yes, does the application issue a `require` for some file under `lib/feets` somewhere?

**Comment by fxn** [comment]
Other two bits of information that would be nice to have are the output of

```
bin/rails runner 'pp Object.const_source_location(:Fleets)'
```

in a setting that reproduces the error. Once you got that, throwing

```ruby
pp caller_locations
```

at the very top of that file would also tell us who is loading said file.

**Comment by roooodcastro** [comment]
Hi Xavier, thanks for the response. I've checked, and `lib` is _not_ in the autoload paths, but this is expected, as I have a monolithic repo that's used also for daemons and other non-pure-Rails stuff, so the files under `lib` should not be always required.

After adding `pp caller_locations`, I've determined that the `Feeds::ProviderIP` namespace is being initially loaded from a `require feeds/providerip/server.rb` in the Newrelic's `rpm_instrumentation.rb` file. So yes, this is being loaded with an explicit require.

However, this still doesn't explain why the "root" module file `app/models/feeds/providerip.rb` is being completely ignored, as it defines some methods for the module. I have the exact same structure (and `require`s) for other namespaces and they all work fine, except this one which uses the acronym inflection.

**Comment by fxn** [comment]
@roooodcastro perfect, it is normal to not have `lib` in the autoload paths. Asked only to gather context.

So, your code has a namespace where some things are reloadable and others aren't. That is tricky but doable. The only thing is that in order to make it work without problems, you need to be careful about how things are defined.

The reason `app/models/feeds/providerip.rb` is ignored is that when Zeitwerk checks that file, it notices `ProviderIP` is already defined, and therefore concludes _that constant is managed by someone else_. Zeitwerk is able to [reopen namespaces externally managed](https://github.com/fxn/zeitwerk#reopening-third-party-namespaces) to mange child constants, but by design does not execute files that would reopen the class or module itself.

If Zeitwerk didn't do that, on reload, all the original implementation had would be gone. In particular `Fleets::ProviderIP::Server` would not exist. By design, we prevent that you get into that trap.

So, `Fleets::ProviderIP` has to be defined in one place, and cannot be reloadable because you have non-reloadable constants beneath. With the information I have, I guess the easiest solution is to move `app/models/feeds/providerip.rb` to `lib`.

Please let me know if that proposal makes sense, we can explore others too otherwise.

Once we get this right, then we'll talk about the acronym.

**Comment by roooodcastro** [comment]
Hi again,

Thanks for that explanation, I understand what you mean with namespace that's managed by a third-party. I noticed that I was issuing the `require` before Zeitwerk started, so it considered that to be managed by someone else.

I've since moved the `require` to inside a `Rails.configuration.after_initialize` block to ensure Zeitwek would pick up on it, and now everything is loading correctly.

Thank you again

**Comment by fxn** [comment]
Mixing reloadable and non-reloadable is tricky. Let me warn you about a couple of details just in case.

If the application issues a `require` for `feeds/providerip/server.rb` in an `after_initialize`, yes `ProviderIP` is autoloaded from the expected file, and that file will define `Feeds::ProviderIP::Server`. Fine. However, since `Feeds::ProviderIP` is reloadable, if you reload, `Feeds::ProviderIP::Server` no longer exists. In principle, this is broken.

Would moving that `require` to a `to_prepare` callback fix the issue because it is executed on reloads too? No, because `require` is idempotent. You'd need to use `load`, but if another file issued a `require` for the same file expecting idempotence, it would result in loading the file twice. Probably this does not exist in the application, but it is an exercise to show there would be potential broken windows left.

The correct way to deal with this is to identify what cannot be reloadable. Not because of Zeitwerk, the library is only making you think about what logically works. In this case, `Feeds::ProviderIP` shouldn't be reloadable because `Feeds::ProviderIP::Server` is not. But you could at the same time have `Feeds::ProviderIP::Foo` to be reloadable itself.

That is only feedback in case it makes you think about the consequences. If the solution you wrote is OK for you, then please go ahead.

One final note about acronyms: "ProvideIP" is not an acronym. And acronym is all capital letters: "HTML", "JSON", "ETA", etc. So, the proper way to configure the inflector would be

```ruby
inflect.acronym 'ProviderIP'
```

and basenames would be `provider_ip`.
