### ISSUE TITLE
Is there a way to get zeitwerk original object within rails 6 ?

### ISSUE THREAD

**Issue by zw963** [fxn/zeitwerk#201]
Thanks

**Comment by fxn** [comment]
Yes, you can see how [in the Rails documentation](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#rails-autoloaders).

**Comment by zw963** [comment]
Oops,  those document almost the end of page ...

Thank you!

**Comment by fxn** [comment]
Yep! It's at the bottom because the idea is that Rails integrates the library on your behalf.

So, it is Rails who creates the loaders, configures root directories, enables reloading if needed, configures eager loading exclusions if any, etc. Also, inflections go typically via Active Support.

It is only in edge cases that you need to reach for the loaders instances.

The order in the guide reflects that (and there's a table of contents in the sidebar to have a bird's eye of all covered).
