### ISSUE TITLE
It does not appear to be reloading the code on changes.

### ISSUE THREAD

**Issue by cj** [fxn/zeitwerk#21]
This issue is in reference to https://github.com/fxn/zeitwerk/issues/19#issuecomment-472522542.

Adding code to a controller once the server has loaded does not get executed/updated.

### Steps to reproduce:

- rails new no-reload -d postgresql -m https://raw.githubusercontent.com/excid3/jumpstart/c6c0de0/template.rb
- cd no-reload
- foreman start
- visit http://localhost:5000/users/sign_up
- add the line `after_action { pp 'foo' }` to `app/controllers/application_controller.rb`
- refresh the page
- does not out put 'foo' to the console.

### Expected outcome:

- print `foo` to the console

### Current work around:

-  add `config.autoloader = :classic` to `config/application.rb`

### Screencast demonstrating issue:

https://cl.ly/577db63e745a

---

@fxn here is the Zeitwerk trace https://gist.github.com/cj/ffc8b578412034cebdd410bf534e4ab0

**Comment by fxn** [comment]
Thanks a lot for the screencast and detailed reproduction steps, it is a pleasure to work on an issue so well reported.

This turns to be an issue in the Rails integration. I have created https://github.com/rails/rails/issues/35618 and explained in a comment what is happening. Going to close here since Zeitwerk itself is good.

Thanks!

**Comment by cj** [comment]
My pleasure -- thank _you_ for your contribution to open source and taking the time to look at and fix the issues!

I hope you have a great weekend!
