### ISSUE TITLE
Is it possible for a gem to offer opt-in eager loading?

### ISSUE THREAD

**Issue by timrogers** [fxn/zeitwerk#220]
I am considering integrating Zeitwerk into a gem. 

In the examples in the readme, `#eager_load` is called in the gem code after the "root module" is defined, a bit like this:

```
module MyGem
end

loader.eager_load
```

Instead of the gem making the decision to eager load, is it possible for the gem to allow the user to decide if they want to eager load or lazy load? 

I am imagining something like this:

```
module MyGem
  def self.eager_load
    # Optionally eager load here
  end
end
```

**Comment by fxn** [comment]
@timrogers Yes, that is possible.

The reason the example puts the call at the bottom is that you cannot eager load before the namespace is defined, as this alternative would attempt:

```ruby
loader.eager_load

module MyGem
end
```

because it would try to eager load `my_gem.rb` and have `MyGem` defined, and precisely we are in the middle of loading that file!

But located in a method as in your suggestion would work fine.

**Comment by fxn** [comment]
Let me add that Ruby on Rails invokes `Zeitwerk::Loader.eager_load_all` ([docs](https://github.com/fxn/zeitwerk#global-eager-load)) if `config.eager_load` is true. That eager loads all gem dependencies using Zeitwerk.
