### ISSUE TITLE
safe_constantize requires files defined in a constant hash

### ISSUE THREAD

**Issue by tococorocko** [fxn/zeitwerk#225]
Hi,
first of all thanks for your great work for the ruby (on rails) community. I have a question regarding `safe_constantize` and constant hashes in classes:

Rails version: 6.0.5.x
Ruby version: 2.7.5

So I have a Rails application with a model class `Foo`, which defines a constant hash `SECTIONS` with other model classes `BAR` and `BAZ`:

```

# app\models\foo.rb
class Foo < ActiveRecord::Base
  SECTIONS = {
     :bar => Bar,    #app\models\bar.rb
     :baz => Baz     #app\models\baz.rb
  }
end

```

The constant hash is used some place else to get the class and do some queries depending on a section `klass = Foo::SECTIONS[section]`. Now an external Gem comes into play, which at one point does `klass = "Foo".safe_constantize`.

### classic
In `:classic` `safe_constantize` just returns the constant via `ActiveSupport::Inflector#constantize` --> `constant.const_get(name)`.
 
### zeitwerk
In `:zeitwerk`-mode `safe_constantize` follows the same path (`ActiveSupport::Inflector#constantize` --> `constant.const_get(name)`), but then Zeitwerk requires the file again (see `lib/zeitwerk/kernel.rb:25 Object#require`). It not only requires `Foo`, but it also requires the classes/constants (`Bar` and `Baz`) inside the constant `SECTIONS`. This leads to problems in the gem with `can't add a new key into hash during iteration`.

Is `safe_constantize` meant to require the constant/class with all constants inside? If yes, what would be the correct way to "just" get the constant "Foo"?

Thank you!

**Comment by fxn** [comment]
Yes, both modes load the constants inside, because they are referenced at class-level (rather than, say, inside a method body).

Let's forget autoloaders, let's imagine a regular Ruby library. If you ask Ruby to load the file `foo.rb`, Ruby is going to interpret its contents. In paticular, it defines a constant called `SECTIONS` in the `Foo` class, and in order to initialize `SECTIONS` it needs to evaluate the keys and values of the hash literal.

The keys are literals themselves (symbols), and the values are class objects. You'd need to `require "bar"` and `require "baz"` for that file to be loadable, because you need `Bar` and `Baz` to be defined at that point.

All this happens on the go, before you have finished to interpret `foo.rb`.

So. If you have an autoloader in place, you can spare the `require` calls, but the class objects `Bar` and `Baz` are still needed. If they were not loaded already, the autoloader is going to load them on the spot and resume.

As you see, it is expected that loading `foo.rb` triggers loading `Bar` and `Baz` if they were not already loaded. And this happens both in `classic` and in `zeitwerk` mode. As it would happen via `require` in a Ruby program without autoloader.

OK, now that we are on the same page regarding these expectations, could you reproduce in a minimal application?

**Comment by fxn** [comment]
If you try to reproduce and don't succeed, we could try to debug in your application as plan B.

**Comment by tococorocko** [comment]
Thank you for the answer and offer. I was just in the process of answering 😊

I tried to reproduce the behaviour in a minimal application, but everything worked fine... So I went back and investigated further and the problem seems to be an error in one of the classes, which prevented the class to load completely. The Gem expects the class/constant to be present.

The error happens only in `:zeitwerk`-mode:

```
# from Rails.autoloaders.log!
Zeitwerk@rails.main: constant Validators loaded from file <NameOfApp>/lib/validators.rb
NameError: uninitialized constant Validators::HtmlLengthValidator
```

There is a validator module directly under `lib`:

```
module Validators
    # defines some things
end
```

And there are namespaced validators under `lib/validators`:

```
module Validators
    class HtmlLengthValidator < ActiveModel::Validator
    end
end
```

```
#models/foo.rb
class Foo
    validates_with Validators::HtmlLengthValidator ....
end

```

```
#application.rb
...
    config.load_defaults 6.0
    config.autoloader = :zeitwerk

    config.autoload_paths += %W(#{root}/lib)
    config.eager_load_paths += %W(#{root}/lib)
...

```

```
# puts puts ActiveSupport::Dependencies.autoload_paths
<NameOfApp>/app/models/extensions
<NameOfApp>/lib
<NameOfApp>/app/cells
<NameOfApp>/app/controllers
<NameOfApp>/app/controllers/concerns
<NameOfApp>/app/decorators
<NameOfApp>/app/helpers
<NameOfApp>/app/jobs
<NameOfApp>/app/lib
<NameOfApp>/app/mailers
<NameOfApp>/app/models
<NameOfApp>/app/models/concerns
<NameOfApp>/app/use_cases
...
```

Is there a way to get the same behaviour in :zeitwerk as in :classic for the autoloaded lib directory? The validator example above is just one of many. 
(The same happens, when I move the files under `app/lib/` as often suggested.)

But there might be another problem with STI... I need some more time to investigate😅

Please let me know If I should ask this question somewhere else (and if so, feel free to close the issue).

**Comment by fxn** [comment]
Ruby interprets files and if an exception is raised at any point while the file is loaded (a `NameError` in this case), no side-effect is reversed. For example, you may have the `Foo` model defined, but a bunch of its methods undefined, or even none defined at all. The consequences can be many and are out of your control. The program has been left in an inconsistent state and you generally need to reset.

This is not related to autoloading, it is how Ruby works.

Let's focus on why `Validators::HtmlLengthValidator` is not found, it should be found. You enabled logging, could you please trigger the error again and share the traces?

**Comment by fxn** [comment]
Could it be the case that your application defines an acronym "HTML"? What does

```
bin/rails runner 'puts "html".camelize'
```

print?

**Comment by fxn** [comment]
This is all very strange. Let me share some remarks:

* The autoloaders know nothing about STI or descendants, they just deal with missing constants and the file system.
* If your application loaded everything in `classic` mode and eager loading was disabled, someone was loading the classes somehow.
* The `StiPreload` preload technique is not specific to `zeitwerk` mode, it is a way to preload what you need. In your case, if there are two databases, you may need to preload yourself and do not use that module. Maybe understand how did the application preload before.
* I don't understand how is all this related to the `NameError` raised for `Validators::HtmlLengthValidator`. Why did the error happen? How is that connected to STI?
* Autoloading does not distinguish gem-code from application-code, it is all Ruby code living in the same process, without boundaries. There is no different autoloading from a Rails model or from a gem (as long as the gem autoloads without caching the reference, it has to play nicely with reload).

OK, having said that, you application having two databases may need to preload the STI in a special way. Let's see if we can understand how that was done before and whether that could be a good idea now.

**Comment by fxn** [comment]
Hey, I don't think there's an issue with Zeitwerk itself in this ticket.

The bottom line is: In Active Record, STIs of certain depth need to be eager loaded so that the whole hierarchy is known.

I'll revise the `StiPreload` module and/or documentation (which belongs to the Rails project), but in your particular case, I'd recommend deleting `StiPreload` from your code base and writing an initializer like this:

```ruby
# config/initializers/preload_sti.rb
unless Rails.configuration.eager_load
  Rails.configuration.to_prepare do
    # 1. fetch the distinct class names in your STI tables from all tenants
    # 2. constantize them all
  end
end
```

With that, I'll close, but don't hesitate to followup if you need more help.
