### ISSUE TITLE
undefined method `root_dirs' 

### ISSUE THREAD

**Issue by isabellecochrane** [fxn/zeitwerk#238]
undefined method `root_dirs' for #<Zeitwerk::Loader:0x00007efe38ea3ef8 @inflector=ActiveSupport::Dependencies::ZeitwerkIntegration::Inflector

Updating rails has updated zeitwerk to 2.6.6 and now this error is shown

**Comment by fxn** [comment]
@isabellecochrane Can you share a stack trace please? Where is this method used? Which version of Rails?

**Comment by cfurrow** [comment]
Could it be that you use packwerk gem? There was a recent issue there regarding `root_dirs`

https://github.com/Shopify/packwerk/pull/254/files

**Comment by fxn** [comment]
The method `root_dirs` is private, and some code is using it. Maybe `packwek` as @cfurrow suggested.

It is likely that this is not an issue with Zeitwerk itself, but with some other project. If you are able to provide more information, I'd be glad to help determine who is invoking that method to fully understand the situation and know how to proceed.

Otherwise, I like to keep issues and PRs to zero and would eventually close.

**Comment by fxn** [comment]
A week has passed, and I suspect this is due to some 3rd party code using a private API that changed. So I am going to close.

Still willing to help identify that code if you want, please just followup here in that case.
