### ISSUE TITLE
Add CHANGELOG.md to gem

### ISSUE THREAD

**Issue by rocket-turtle** [fxn/zeitwerk#294]
Hi,

is there a reason why the [CHANGELOG.md](https://github.com/fxn/zeitwerk/blob/main/CHANGELOG.md) is not added to the `spec.files` in _zeitwerk.gemspec_?

If someone compares two versions of a gem (e.g with https://my.diffend.io/gems/zeitwerk/2.6.13/2.6.14) it is easier to follow what changed via the changes in the changelog.

**Comment by fxn** [comment]
The reason is that I don't see why to ship the CHANGELOG. The gem does not include the tests either, or `Rakefile`, the project rules, etc.

When I need to upgrade a gem, I don't look at a diff. There are internals there I should not care about, generally. I go to GitHub to see the CHANGELOG for user-level information about the changes.

**Comment by fxn** [comment]
The [gem metadata](https://github.com/fxn/zeitwerk/blob/b5256436ba1a696826702febb524aabb9b84bfca/zeitwerk.gemspec#L23) does have the URL of the CHANGELOG:

**Comment by fxn** [comment]
By now, I'll keep it as it is.

The gem is something you ship for execution, it is intentionally a subset of the repository. To know what has changed you read the published CHANGELOG or release notes.

I am open to reconsider if there is a convincing use case but, for now, I'll close.
