### ISSUE TITLE
Zeitwerk 2.1.5 breaks: uninitialized constant

### ISSUE THREAD

**Issue by ddfreyne** [fxn/zeitwerk#45]
Zeitwerk 2.1.5 can raise an “uninitialized constant” error while 2.1.4 works fine.

### Steps to reproduce

OK:

1. Clone https://github.com/ddfreyne/zeitwerk-nanoc-core-mini
2. Run `bundle` (this installs Zeitwerk 2.1.4)
3. Run `bundle exec ruby test.rb`

This prints

```
I am the thing! I exist!
Nanoc::Core::Thing
```

Let’s make it fail:

1. Change the `zeitwerk` line in Gemfile to `gem 'zeitwerk', '= 2.1.5'` (was `= 2.1.4`)
2. Run `bundle`
3. Run `bundle exec ruby test.rb`

This prints

```
`const_get': uninitialized constant NanocCore (NameError)
```

### Expected results

Same behavior as Zeitwerk 2.1.4.

### Actual results

Raises `uninitialized constant NanocCore (NameError)`

### Extra details

Traceback:

```
Traceback (most recent call last):
	13: from test.rb:5:in `<main>'
	12: from test.rb:5:in `require'
	11: from /Users/denis/Desktop/zeitwerk-nanoc-core-mini/lib/nanoc-core.rb:3:in `<top (required)>'
	10: from /Users/denis/Desktop/zeitwerk-nanoc-core-mini/lib/nanoc-core.rb:3:in `require'
	 9: from /Users/denis/Desktop/zeitwerk-nanoc-core-mini/lib/nanoc/core.rb:20:in `<top (required)>'
	 8: from /usr/local/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.5/lib/zeitwerk/loader.rb:341:in `eager_load'
	 7: from /usr/local/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.5/lib/zeitwerk/loader.rb:341:in `synchronize'
	 6: from /usr/local/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.5/lib/zeitwerk/loader.rb:348:in `block in eager_load'
	 5: from /usr/local/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.5/lib/zeitwerk/loader.rb:631:in `each_abspath'
	 4: from /usr/local/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.5/lib/zeitwerk/loader.rb:631:in `foreach'
	 3: from /usr/local/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.5/lib/zeitwerk/loader.rb:634:in `block in each_abspath'
	 2: from /usr/local/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.5/lib/zeitwerk/loader.rb:352:in `block (2 levels) in eager_load'
	 1: from /usr/local/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.5/lib/zeitwerk/loader.rb:669:in `const_get_if_autoload'
/usr/local/lib/ruby/gems/2.6.0/gems/zeitwerk-2.1.5/lib/zeitwerk/loader.rb:669:in `const_get': uninitialized constant NanocCore (NameError)
```

**Comment by fxn** [comment]
I see, let me explain.

Up to 2.1.4, eager loading was done with `require`. This was too weak, because `require` will happily intepret whatever is in the file. That means, projects that do not follow the documented file structure could eager load, when they should not (because the file structure does not comply with the requirements).

This inconsistency was raised by @casperisfine and had practical consequences beyond a mere theoretical contract violation. Shopify had Zeitwerk running in CI and in production, to susprisingly find that development needed some further adjustments because some files didn't comply and could not autoload.

To be consistent, [we eager load now with `const_get`](https://github.com/fxn/zeitwerk/commit/8977e45db924a19465d15a22fdb3ed7e856cdc2b). I considered this to be a bug, and that is why the change happened in a patch release.

In the case of the mini repo to reproduce (thanks a lot!), the file `nanoc-core.rb` belongs to the root directory but does not define the corresponding constant. That is supported, but you need to tell Zeitwerk to ignore the file:

```ruby
loader.ignore("#{__dir__}/../nanoc-core.rb")
```

Also, `nanoc/core.rb` does not define `Nanoc::Core`, so you can either define a module there

```module
module Nanoc
  module Core
  end
end
```

or ignore the file too:

```ruby
loader.ignore(__FILE__)
```

Of course you can also reorganize a bit that setup if the internal organization is private to the gem... You see the rules of the game.

**Comment by ddfreyne** [comment]
Perfect, that works — and thank you for the detailed explanation!
