### ISSUE TITLE
Zeitwerk doesn't auto reload our code even with enable_reloading set to "true"

### ISSUE THREAD

**Issue by arg** [fxn/zeitwerk#50]
We're using Grape + ActiveRecord combo as our API service. Gems/Zeitwerk initializer looks like this:
```ruby
# environment.rb

ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', __FILE__)
ENV['RACK_ENV'] ||= 'development'

require 'bundler' and Bundler.require(:default, ENV['RACK_ENV'])
loader = Zeitwerk::Loader.new
%w(api models helpers lib).each { |dir| loader.push_dir(dir) }
loader.enable_reloading unless ENV['RACK_ENV'] == 'production'
loader.setup
```

later we call this code in our Rack app:
```ruby
require_relative 'environment'

# mount Grape app, etc.
```

We want auto code reloading to work in `development` environment which is default in our setup. Current environment is defined by `RACK_ENV` env variable, no `RAILS_ENV` is used.

For some reason this setup doesn't work. Changes made to files in `api`, `lib` or other directories don't trigger code reloading. I believe there is no issue in Zeitwerk code, we're just missing something. Is it because of the absence of `RAILS_ENV` variable? We'd like to figure it out.

**Comment by fxn** [comment]
Zeitwerk offers code reloading as a method call:

```ruby
loader.reload
```

but that method has to be invoked by the parent project.

If Grape doesn't have file watching built-in, you could try to integrate [listen](https://github.com/guard/listen). For example (off the top of my head, untested):

```ruby
unless ENV['RACK_ENV'] == 'production'
  loader.enable_reloading
  Listen.to('api', 'models', 'helpers', 'lib') { loader.reload }.start
end
loader.setup
```

This is not thread-safe, but it is simple if you don't need thread-safety in development. The README outlines how to accomplish that with shared lock, otherwise.

**Comment by arg** [comment]
TIL, thank you @fxn. I thought Zeitwerk has some built-in file watcher.
