### ISSUE TITLE
Unclear why the main module should be defined after Zeitwerk setup

### ISSUE THREAD

**Issue by mdesantis** [fxn/zeitwerk#77]
The README has the following example code:

https://github.com/fxn/zeitwerk/blob/757dd734340024e487bd9678dcf80a567064bfdc/README.md#L59-L69

Is there any reason for the main module to be declared after Zeitwerk setup? I'm asking that because it prevents gem developers to have the Zeitwerk setup in another file under the main module namespace, like this:

```ruby
# lib/mygem.rb

module MyGem
end

require 'zeitwerk'
require 'mygem/zeitwerk_inflector'

loader = Zeitwerk::Loader.for_gem
zeitwerk_inflector_abs_path = "#{__dir__}/mygem/zeitwerk_inflector.rb"
loader.inflector = MyGem::ZeitwerkInflector.new
loader.ignore zeitwerk_inflector_abs_path
loader.setup
```

```ruby
# lib/mygem/zeitwerk_inflector.rb

class MyGem::ZeitwerkInflector < Zeitwerk::Inflector
  def camelize(basename, _abspath)
    case basename
    when 'mygem'
      'MyGem'
    else
      super
    end
  end
end
```

Actually, I'm using the setup above in one of my projects and I haven't noticed any issues so far, so I wonder if the instructions order in the example is just accidental or not. 

Also, I wonder if `loader.eager_load` order instruction is accidental or not too :confused:

**Comment by casperisfine** [comment]
> Is there any reason for the main module to be declared after Zeitwerk setup?

No, no particular reason, it can be define before or after the actual namespace, it doesn't matter.

I can't answer for @fxn (he is in vacation this week) but I suppose it's just better to define it as early as possible so that autoloading is immediately setup for when you start referencing autoloaded constants.

> Also, I wonder if loader.eager_load order instruction is accidental or not too 

Yes and no. You could do it earlier, but this is just in case you have some important things defined in the main module, e.g.:

```ruby
# lib/my_gem.rb
# ...
loader.eager_load

module MyGem
  SOME_CONSTANT = 1
end

# lib/my_gem/foo.rb
module MyGem
  module Foo
    SOME_CONSTANT + 1
  end
end
```

So yeah, better to call setup as early as possible, and eager_load as late at the end of the main module, but your mileage may vary.

**Comment by mdesantis** [comment]
@casperisfine thank you for the answer, it's very interesting. What if these informations are added to the README? I could open a PR if it is welcome

**Comment by casperisfine** [comment]
That would be @fxn's call.

**Comment by fxn** [comment]
What @casperisfine said.

The way to do the setup is flexible, the README just shows one way that makes sense for most libraries.

You setup _before_ the module definition in case there are referenced constants. For example, if the module includes other modules defined in the library.

```ruby
module MyGem
  include Foo # has to be able to autoload MyGem::Foo already at this point.
end
```

If that is not the case, Zeitwerk setup can be done later technically.

Regarding the `eager_load` call suggested at the bottom, thing is you are generally not ready to eager load before the namespace is defined. For starters, if you put the call before the module definiton Zeitwerk would try to eager load _lib/my_gem.rb_ because `MyGem` is not defined, circularity would prevent that and you get a `NameError`.

The entry point _lib/my_gem.rb_ is an edge case in Zeitwerk, there is an inception situation there that makes it delicate, and took me time to reach a compromise about usage interface and implementation.

Let me write a doc patch for this.

**Comment by fxn** [comment]
I have added clarifications for the topics discussed here in the commits referenced above.

Please let me know if you have any further questions.

**Comment by mdesantis** [comment]
The new documentation looks great to me, thank you for the clarification!
