### ISSUE TITLE
Fallback for older Ruby versions

### ISSUE THREAD

**Issue by pitr-ch** [fxn/zeitwerk#8]
Could zeitwerk provide a fallback that would eager load everything (probably also with disabled reloading) on Ruby implementations which do not fulfill the zeitwerk's requirements? That would potentially allow for wider adoption. 

I am considering to use it in concurrent-ruby. It still supports 1.9 so I need a fallback, I started thinking about adding fallback in concurrent-ruby however it seems it would be better and beneficial to have in the zeitwerk itself.

**Comment by fxn** [comment]
Let's explore that.

How do you imagine usage? Would you issue `require` calls as usual in your code base, and then just leverage eager loading when a parent application calls `Zeitwerk.eager_load_all`?

**Comment by pitr-ch** [comment]
Thinking only from the user's perspective, not considering technical feasibility. As a user I'd like to not need to change anything in the loader setup of the library (with an exception of opting-in the fallback support). The loader would be used in the same way as if on Ruby 2.4.4 and above. The loader would fallback to different behavior depending on the current Ruby implementation.

So e.g. in concurrent-ruby, the `concurrent.rb` would setup the loader and users of concurrent-ruby would only require this file (this is the only officially supported way to load the c-r at the moment). Any other constant would be auto-loaded. If it's an older Ruby the loader.setup call would eager load all the files instead (which is what happens now in concurrent-ruby anyway).

What are your thoughts?

**Comment by fxn** [comment]
I'll reflect about it for a bit. Nevertheless let me comment that eager loading implies autoloading.

Code may be

```ruby
module CountriesHelper
  # Cache countries for performance, a new country needs a reboot.
  ALL = Country.all
end
```

or 

```ruby
class Hotel
  include Hotel::Pricing
end
```

That is, loading files in general has to be ready to resolve constants used at the top-level.

**Comment by fxn** [comment]
Yeah, so I think by now we are going to close this one.

The main point of this gem is autoloading, really. Eager loading is kind of a nice-to-have that Zeitwerk is able to provide _because it is in charge of autoloading_. Client code using Zeitwerk only for eager loading because it is running on previous Ruby versions should issue `require` calls, and that is not the spirit of Zeitwerk. A code base managed by Zetiwerk ideally has no `require` or `autoload` calls for its own files (except for adapter patterns and other documented use cases of `ignore`).

So, the source code would get complicated to support something in a direction that right now I don't quite see for the library.

Thanks anyway for the discussion!
