### ISSUE TITLE
Append subdir to root namespace?

### ISSUE THREAD

**Issue by agis-theodoropoulos** [fxn/zeitwerk#84]
My use case is a gem. I would like to have the constants defined in its `models/` directory belong to the root namespace, like so:

```
lib/my_gem.rb                         -> MyGem
lib/my_gem/models/flip.rb             -> MyGem::Flip
lib/my_gem/models/flop.rb             -> MyGem::Flop
lib/my_gem/models/concerns/widget.rb  -> MyGem::Widget
lib/my_gem/bar/flip.rb                -> MyGem::Bar::Flip
lib/my_gem/bar/flop.rb                -> MyGem::Bar::Flop
```

Is this possible?

**Comment by fxn** [comment]
You need to flip the directories:

```
lib/my_gem.rb                         -> MyGem
lib/models/my_gem/flip.rb             -> MyGem::Flip
lib/models/my_gem/flop.rb             -> MyGem::Flop
lib/models/concerns/my_gem/widget.rb  -> MyGem::Widget
lib/my_gem/bar/flip.rb                -> MyGem::Bar::Flip
lib/my_gem/bar/flop.rb                -> MyGem::Bar::Flop
```

In order to have uniformity under `lib` if you liked it, maybe the gem could define some additional subdirectories, but the example above would work as is.

Then, in `my_gem.rb` define a loader for that layout (untested):

```ruby
loader = Zeitwerk::Loader.new
loader.push_dir(__dir__)                      # for MyGem::Bar::Flip 
loader.push_dir("#{__dir__}/models")          # for MyGem::Flip
loader.push_dir("#{__dir__}/models/concerns") # for MyGem::Widget  
loader.setup
```

Given a root directory that is a descendant of another root directory, Zeitwerk ignores the intermediate segment. So, in the example configuration above, `lib/models` is not considered to be a namespace even if it is a subdirectory of `lib`. Same with `lib/models/concerns`. Which is what we want.

Would that work for you?

**Comment by agis-theodoropoulos** [comment]
Yes, it would. Thanks!

**Comment by xiaohui-zhangxh** [comment]
@agis-theodoropoulos I have the same case, see #94
