### ISSUE TITLE
Are there plans to support transitive module loading?

### ISSUE THREAD

**Issue by mijoharas** [fxn/zeitwerk#9]
Hi,
I'm wondering whether it is a plan for zeitwerk to support searching the ancestor chain when reloading modules (or is this supported already?).

I tried reading the code, but unfortunately I'm not sure if I've fully grokked it.

What I am asking is will this gem currently fix https://github.com/rails/rails/issues/28997, is that planned in the future, or is that not planned?

Thanks for the gem, looks like it will solve a lot of problems!

**Comment by fxn** [comment]
Yes, there are [some tests](https://github.com/fxn/zeitwerk/blob/master/test/lib/zeitwerk/test_ancestors.rb) covering that kind of things not supported in the classic Rails autoloader.

The key point is that `Kernel#autoload` has builtin support in the interpreter. When constant resolution check if a constant is present in some module (ie, walking the nesting outwards), the internal logic is "check if it is present, and if it is not before visiting the next module still check if there is an autoload for it, and if there is one go an autoload the constant".

So Zeitwerk has Ruby semantics because `Kernel#autoload` provides them.

**Comment by mijoharas** [comment]
:raised_hands: brilliant. Thanks! (I saw the tests on ancestors, but it looked like parents to me, so I worried I could be misunderstanding).

Thanks for the quick reply as well!

**Comment by fxn** [comment]
In general, the constant algorithms are not exhaustively tested because that should be already in the Ruby test suite. Nevertheless [I have added coverage](https://github.com/fxn/zeitwerk/commit/a149022606b140eb6f1a36724df2644192d4e9f9) for your sample app structure.
